openapi: 3.0.1
info:
  title: ShippingCompany
  version: "1.0"
servers:
- url: /
paths:
  /api/GlobalEnvoie:
    get:
      tags:
      - GlobalEnvoie
      responses:
        "200":
          description: Success
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags:
      - GlobalEnvoie
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        "200":
          description: Success
  /api/LivraisonRapide:
    get:
      tags:
      - LivraisonRapide
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Root'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Root'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Root'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Root'
            text/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Root'
    post:
      tags:
      - LivraisonRapide
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Root'
          text/json:
            schema:
              $ref: '#/components/schemas/Root'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Root'
          application/xml:
            schema:
              $ref: '#/components/schemas/Root'
          text/xml:
            schema:
              $ref: '#/components/schemas/Root'
          application/*+xml:
            schema:
              $ref: '#/components/schemas/Root'
      responses:
        "200":
          description: Success
components:
  schemas:
    Item:
      type: object
      properties:
        description:
          type: string
          nullable: true
        quantity:
          type: integer
          format: int32
      additionalProperties: false
    ItemJSON:
      type: object
      properties:
        description:
          type: string
          nullable: true
        quantity:
          type: integer
          format: int32
      additionalProperties: false
    Order:
      type: object
      properties:
        orderDetail:
          $ref: '#/components/schemas/OrderDetail'
        items:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Item'
      additionalProperties: false
    OrderDetail:
      type: object
      properties:
        reqID:
          type: string
          nullable: true
        orderDate:
          type: string
          nullable: true
        orderedBy:
          type: string
          nullable: true
      additionalProperties: false
    OrderDetailJSON:
      type: object
      properties:
        reqID:
          type: string
          nullable: true
        orderDate:
          type: string
          nullable: true
        orderedBy:
          type: string
          nullable: true
      additionalProperties: false
    OrderJSON:
      type: object
      properties:
        orderDetail:
          $ref: '#/components/schemas/OrderDetailJSON'
        item:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/ItemJSON'
      additionalProperties: false
    Root:
      type: object
      properties:
        order:
          $ref: '#/components/schemas/OrderJSON'
      additionalProperties: false
